apiVersion: v1
kind: ConfigMap
metadata:
  name: taskapp-config
  namespace: taskapp
data:
  # Database connection (non-secret parts)
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "taskapp"
  DATABASE_USER: "taskapp"

  # Flask config (non-secret)
  FLASK_ENV: "production"
  FLASK_DEBUG: "false"

  # Frontend config
  VITE_API_URL: "https://taskapp.18.169.122.172.nip.io/api"
